const colors = require('tailwindcss/colors');

module.exports = {
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: 'media',
  important: true,
  theme: {
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      '3xl': '1792px',
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '2rem',
      },
    },
    fontSize: {
      '12': '12px',
      '14': '14px',
      '16': '16px',
      '20': '20px',
      '22': '22px',
      '24': '24px',
      '26': '26px',
      '36': '36px',
      '44': '44px',
      '62': '62px',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      mint: '#B4F8C8',
      blue_green: '#75E6DA',
      tiffany: '#A0E7E5',
      fancy_pink: '#F9F1F0',
      black: colors.black,
      white: colors.white,
      gray: colors.trueGray,
      blue: colors.blue,
      green: colors.green,
      red: colors.red,
      yellow: colors.yellow,
    },
    maxHeight: {
      '500': '500px',
    },
    height: {
      '4': '1rem',
      '6': '1.5rem',
      '10': '2.5rem',
      '36': '9rem',
      '60': '15rem',
      '80': '20rem',
      'full': '100%',
      'screen': '100vh',
      'messenger': 'calc(100vh - 60px)',
      'chat': 'calc(100vh - 134px)',
    },
    inset: {
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '40': '10rem',
      '60': '60px',
    },
    boxShadow: {
      DEFAULT: '0px 0px 16px -8px rgb(0, 0, 0, 0.68)',
    },
    zIndex: {
      'header': '999'
    },
    extend: {
      gridTemplateColumns: {
        'layout-desktop': '1fr 2fr 1fr',
        'layout-profile': '1fr 3fr',
        'profile-content': '2fr 1fr',
      },
      gridTemplateRows: {
        'content': '60px 1fr',
      },
      animation: {
        'ping-slow': 'ping 3s infinite',
      }
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
  corePlugins: {
    boxSizing: false,
    float: false,
    clear: false,
    fontFamily: false,
    // inset: false,
    // filter: false,
    brightness: false,
    contrast: false,
    // dropShadow: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    saturate: false,
    sepia: false,
    backdropFilter: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
  },
}
